#!/usr/bin/env python3

import sys
from math import *
from need import *

def	base():
	size = len(sys.argv)
	i = 0
	while i < size:
		i = i + operation.search_operation(i)
		i = i + 1

def main():
	base()
	operation.arrondi()
	operation.display_matrice()
	rename_point.new_point()

main()
