#!/usr/bin/env python3

import sys
from math import *
from need import *

def	base():
	size = len(sys.argv)
	i = 0
	while i < size:
		i = i + operation.search_operation(i)
		i = i + 1

def main():
	base()
	operation.arrondi()
	displaying.display()
	rename_point.new_point()

def display_usage():
	print("Usage :/ ./102architect  x y  [-t, -r, -s, -h]")

if len(sys.argv) < 3:
	display_usage()
	exit(84)
else:
	main()
